# Copyright (c) 2015-2016, Gregory M. Kurtzer. All rights reserved.
# 
# "Singularity" Copyright (c) 2016, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.

BootStrap: debootstrap
OSVersion: xenial
MirrorURL: http://us.archive.ubuntu.com/ubuntu/


%runscript
    echo "This is what happens when you run the container..."

%environment
    LANG=C.UTF-8
    LC_ALL=C.UTF-8

%post
    echo "Hello from inside the container"
    sed -i 's/$/ universe/' /etc/apt/sources.list
    apt update
    apt -y --allow-unauthenticated install vim build-essential wget gfortran bison libibverbs-dev libibmad-dev libibumad-dev librdmacm-dev libmlx5-dev libmlx4-dev graphviz
    echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    echo 'export XDG_RUNTIME_DIR=""' > /etc/profile.d/conda.sh && \
    #wget --quiet https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh -O ~/anaconda.sh && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh
    /opt/conda/bin/conda install --yes dask distributed dask-jobqueue jupyterhub keras zarr scikit-learn dask-labextension -c conda-forge
    /opt/conda/bin/conda update --yes numba pandas h5py
    jupyter labextension install @jupyter-widgets/jupyterlab-manager
    jupyter labextension install @bokeh/jupyter_bokeh
    /opt/conda/bin/conda clean --yes --all
    # install SLURM (needs python)
    # wget https://github.com/SchedMD/slurm/archive/slurm-14-11-11-1.tar.gz && \
    # tar xf slurm-14-11-11-1.tar.gz && cd slurm-slurm* && ./configure && make -j8 install && rm ~/*.tar.gz
    yes | /opt/conda/bin/pip install graphviz

    # mount points for Comet
    mkdir /oasis /scratch /projects
    mkdir -p /usr/lib64/slurm /var/run/munge
